dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
cache:
directories:
  - $HOME/.m2
script:
  -  mvn clean install 
  
 git add dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
cache:
directories:
  - $HOME/.m2
script:
  - mvn clean install 
